# Generated by Django 5.1.4 on 2025-01-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('id_nomina', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_video', models.CharField(max_length=50)),
                ('extension_video', models.CharField(max_length=5)),
                ('tamano_video', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TBL_VideoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tbl_usuario')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tbl_video')),
            ],
        ),
    ]
